#####################################################################
# GitHub Development Workflow Agent Dataset Configuration
#####################################################################
# This configuration generates a dataset for training AI agents on
# common GitHub-based development workflows. It uses chain-of-thought
# reasoning with agent-style tool calling in single-turn mode.
#
# Covers: issue management, pull requests, code review, branching,
# releases, repository operations, and team collaboration.
#####################################################################

dataset_system_prompt: |
  You are a GitHub development assistant with access to the GitHub API.
  When given a development task:
  1. Analyze the request and determine which GitHub operations are needed
  2. Select appropriate tools with correct parameters
  3. Execute the operations and explain the results
  4. Provide clear guidance on next steps if applicable

topic_tree:
  topic_prompt: "GitHub-based software development workflows and operations"
  provider: "gemini"
  model: "gemini-2.5-flash-lite"
  temperature: 0.8
  degree: 3
  depth: 3
  save_as: "github-workflow-topics.jsonl"

data_engine:
  generation_system_prompt: |
    Generate realistic GitHub development scenarios that developers encounter daily.
    Each example should demonstrate practical tool usage with clear reasoning about:
    - Why specific GitHub operations are chosen
    - What parameters are needed and why
    - How to interpret results and take follow-up actions

    Focus on real-world workflows:
    - Issue triage and management
    - Pull request creation and review cycles
    - Branch and release management
    - Code search and navigation
    - Repository maintenance
    - Team collaboration patterns

  instructions: |
    Create scenarios that reflect common developer interactions with GitHub.
    Include context about the development situation (bug reports, feature requests,
    release preparation, code reviews, etc.) and show how to use GitHub tools
    effectively to accomplish the goal. Demonstrate proper sequencing when
    multiple operations are logically connected.

  # Chain of thought with agent mode
  conversation_type: "chain_of_thought"
  reasoning_style: "agent"

  # Single-turn tool use - each example shows one complete interaction
  agent_mode: "single_turn"

  # GitHub MCP tools registry
  tool_registry_path: "gh-mcp-tools.yaml"

  max_tools_per_query: 4
  max_tools_strict: false

  # Model configuration
  provider: "gemini"
  model: "gemini-2.5-flash-lite"
  temperature: 0.5
  max_retries: 5

dataset:
  save_as: "github-workflow-agent-dataset.jsonl"
  creation:
    num_steps: 2
    batch_size: 2
    sys_msg: true
